# fly.toml app configuration file generated for jamesgurney-retrieval-server on 2023-09-17T20:54:02+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jamesgurney-retrieval-server"
primary_region = "ewr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  PRIMARY_REGION = "ewr"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
